name: odoo build

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Trigger'
        required: false
        default: 'Build'
        
env:
 TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')" 
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1 
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          #registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ../12.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
              xh116/odoo:latest
              xh116/odoo:${{ steps.date.outputs.today }}   
